name       : pyrex
version    : 0.9.9
release    : 1
source     :
    - http://www.cosc.canterbury.ac.nz/greg.ewing/python/Pyrex/Pyrex-0.9.9.tar.gz : 5f87df06831d0b3412eb4bc9d3fc2ee7bfae1b913d7da8c23ab2bf5699fb6b50
license    : Apache
component  : programming.python
summary    : Language for writing Python extension modules
description: |
    Language for writing Python extension modules
builddeps  :
    - pkgconfig(python-2.7)
build      : |
    python setup.py build
install    : |
    python setup.py install -O0 --root=%installroot%
